language: csharp
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      env: HOSTOS=Darwin
addons:
  homebrew:
    taps: xamarin/xamarin-android-windeps
    packages:
    - ninja
    - xamarin/xamarin-android-windeps/mingw-zlib
    update: true
  apt:
    packages:
    - ninja-build
    update: true
install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew upgrade https://raw.githubusercontent.com/Homebrew/homebrew-core/a6542037a48a55061a4c319e6bb174b3715f7cbe/Formula/mingw-w64.rb || true ; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install mingw-w64 || true ; fi
script:
- ./build_native
- ./build_windows
- nuget pack libzip.nuspec
- msbuild /restore libZipSharp.sln
- msbuild /restore libZipSharp.csproj /t:Pack